// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {updater} from '../models';
import {service} from '../models';
import {model} from '../models';

export function CheckAuthOnStartup():Promise<app.CurrentUserResponse>;

export function CheckUpdate():Promise<updater.Asset>;

export function DeleteCache():Promise<void>;

export function DeleteFiles():Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function DeleteLogs():Promise<void>;

export function DownloadAndLaunch(arg1:string):Promise<app.LaunchResponse>;

export function DownloadAndLaunchWithServer(arg1:string,arg2:string):Promise<app.LaunchResponse>;

export function GetAllNews():Promise<Array<service.NewsArticle>>;

export function GetAuthToken():Promise<string>;

export function GetCrashReports():Promise<Array<service.CrashReport>>;

export function GetCurrentUser():Promise<app.CurrentUserResponse>;

export function GetCustomUser():Promise<model.AzuriomUser>;

export function GetDiscordRPC():Promise<boolean>;

export function GetInstanceInfo():Promise<model.InstanceModel>;

export function GetLatestNews():Promise<service.NewsArticle>;

export function GetLauncherVersion():Promise<string>;

export function GetLocalGameVersion(arg1:string):Promise<string>;

export function GetLogs():Promise<string>;

export function GetNick():Promise<string>;

export function GetPreReleaseVersions():Promise<app.VersionsResponse>;

export function GetReleaseVersions():Promise<app.VersionsResponse>;

export function GetServers():Promise<Array<service.ServerWithUrls>>;

export function HasPlayerRole():Promise<boolean>;

export function Login(arg1:app.LoginRequest):Promise<app.AuthResponse>;

export function Logout():Promise<app.AuthResponse>;

export function OpenFolder():Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function SelectInstance(arg1:string):Promise<void>;

export function SetDiscordRPC(arg1:boolean):Promise<void>;

export function SetLocalGameVersion(arg1:string,arg2:string):Promise<void>;

export function SetNick(arg1:string,arg2:string):Promise<void>;

export function SyncInstanceState():Promise<void>;

export function Update():Promise<void>;

export function UpdateInstanceBranch(arg1:string):Promise<void>;

export function UpdateInstanceName(arg1:string):Promise<void>;

export function UpdateInstanceVersion(arg1:string):Promise<void>;

export function ValidateInstance():Promise<void>;

export function ValidatePlayerAccess():Promise<void>;
