// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthOnStartup() {
  return window['go']['app']['App']['CheckAuthOnStartup']();
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function DeleteCache() {
  return window['go']['app']['App']['DeleteCache']();
}

export function DeleteFiles() {
  return window['go']['app']['App']['DeleteFiles']();
}

export function DeleteGame(arg1) {
  return window['go']['app']['App']['DeleteGame'](arg1);
}

export function DeleteLogs() {
  return window['go']['app']['App']['DeleteLogs']();
}

export function DownloadAndLaunch(arg1) {
  return window['go']['app']['App']['DownloadAndLaunch'](arg1);
}

export function DownloadAndLaunchWithServer(arg1, arg2) {
  return window['go']['app']['App']['DownloadAndLaunchWithServer'](arg1, arg2);
}

export function GetAllNews() {
  return window['go']['app']['App']['GetAllNews']();
}

export function GetAuthToken() {
  return window['go']['app']['App']['GetAuthToken']();
}

export function GetCrashReports() {
  return window['go']['app']['App']['GetCrashReports']();
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetCustomUser() {
  return window['go']['app']['App']['GetCustomUser']();
}

export function GetDiscordRPC() {
  return window['go']['app']['App']['GetDiscordRPC']();
}

export function GetInstanceInfo() {
  return window['go']['app']['App']['GetInstanceInfo']();
}

export function GetLatestNews() {
  return window['go']['app']['App']['GetLatestNews']();
}

export function GetLauncherVersion() {
  return window['go']['app']['App']['GetLauncherVersion']();
}

export function GetLocalGameVersion(arg1) {
  return window['go']['app']['App']['GetLocalGameVersion'](arg1);
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetNick() {
  return window['go']['app']['App']['GetNick']();
}

export function GetPreReleaseVersions() {
  return window['go']['app']['App']['GetPreReleaseVersions']();
}

export function GetReleaseVersions() {
  return window['go']['app']['App']['GetReleaseVersions']();
}

export function GetServers() {
  return window['go']['app']['App']['GetServers']();
}

export function HasPlayerRole() {
  return window['go']['app']['App']['HasPlayerRole']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function OpenFolder() {
  return window['go']['app']['App']['OpenFolder']();
}

export function OpenLogsFolder() {
  return window['go']['app']['App']['OpenLogsFolder']();
}

export function SelectInstance(arg1) {
  return window['go']['app']['App']['SelectInstance'](arg1);
}

export function SetDiscordRPC(arg1) {
  return window['go']['app']['App']['SetDiscordRPC'](arg1);
}

export function SetLocalGameVersion(arg1, arg2) {
  return window['go']['app']['App']['SetLocalGameVersion'](arg1, arg2);
}

export function SetNick(arg1, arg2) {
  return window['go']['app']['App']['SetNick'](arg1, arg2);
}

export function SyncInstanceState() {
  return window['go']['app']['App']['SyncInstanceState']();
}

export function Update() {
  return window['go']['app']['App']['Update']();
}

export function UpdateInstanceBranch(arg1) {
  return window['go']['app']['App']['UpdateInstanceBranch'](arg1);
}

export function UpdateInstanceName(arg1) {
  return window['go']['app']['App']['UpdateInstanceName'](arg1);
}

export function UpdateInstanceVersion(arg1) {
  return window['go']['app']['App']['UpdateInstanceVersion'](arg1);
}

export function ValidateInstance() {
  return window['go']['app']['App']['ValidateInstance']();
}

export function ValidatePlayerAccess() {
  return window['go']['app']['App']['ValidatePlayerAccess']();
}
